# Generated by Django 6.0.2 on 2026-03-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('kids', 'Kids'), ('mens', 'Mens'), ('electronics', 'Electronics')], default='mens', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
